### ISSUE TITLE
new function file upload

### ISSUE THREAD

**Issue by opencartmasterbr** [DenisCunha/sumula-tiro-defensivo-idsc#1]
$extensao = strtolower(substr($_FILES['imagem']['name'], -4));
$novo_nome = date('d-m-Y-H-i-s') . $extensao;
$diretorio = getcwd() . '/asset/img/';

if(move_uploaded_file($_FILES['imagem']['tmp_name'], $diretorio.$novo_nome)) {
    $imagesrc = "asset/img/".$novo_nome;
} else {
    $imagesrc = "asset/img/padrao.png";
}

**Comment by DenisCunha** [comment]
ok

**Comment by DenisCunha** [comment]
add
